%Author- Mrigakshi Pandey (2015UEC1380)
% Sine wave at different frequencies
%.......................................

close all;
clear all;
clc;

n=1:1:50;

f=sin(4*pi*n);
subplot(3,1,1);
stem(f);
title('sin(4n)');
xlabel('time-> (sec)');
ylabel('Value');

f2=sin(2*pi*n);
subplot(3,1,2);
stem(f2);
title('sin(4*pi*n)');
xlabel('time-> (sec)');
ylabel('Value');

f3=sin(2*pi*n/3);
subplot(3,1,3);
stem(f3);
title('sin(2/3*pi*n)');
xlabel('time-> (sec)');
ylabel('Value');
dim = [0.1 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');

