

%Author- Mrigakshi Pandey (2015UEC1380)
% Sine wave at different frequencies
%.......................................
 
close all;
clear all;
clc;
 
t=0:0.0001:0.5;
 
f=sin(2*pi*50*t);
subplot(3,1,1);
plot(t,f);
title('Sine Wave f = 50Hz');
xlabel('time-> (sec)');
ylabel('Function sin(2*pi*f*t)');
 
f2=sin(2*pi*100*t);
subplot(3,1,2);
plot(t,f2);
title('Sine Wave f = 100Hz');
xlabel('time-> (sec)');
ylabel('Function sin(2*pi*f*t)');
 
f3=sin(2*pi*150*t);
subplot(3,1,3);
plot(t,f3);
title('Sine Wave f = 150Hz');
xlabel('time-> (sec)');
ylabel('Function sin(2*pi*f*t)');
dim = [0 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');


