%Author- Mrigakshi Pandey (2015UEC1380)
% Convolution by Toeplitz Matrix
%.......................................

close all;
clear all;
clc;

X=input('Input your Vector: ');
a=length(X);
tx=1:1:a;

Y=input('Input another Vector for Convolution: ');
b=length(Y);
ty=1:1:b;
subplot(2,2,1);
stem(tx,X);
title('First Vector');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,2);
stem(ty,Y);
title('Second Vector');
xlabel('Index ->');
ylabel('Value ->');
n=a+b-1;
A=conv(X,Y);

Y=Y';
X=[X,zeros(1,n-a)]';

Xt=X;

for i=1:1:b-1
    Xt=[Xt,circshift(X,1)];
    X=circshift(X,1);
end

Z=Xt*Y;
Z=Z';
t=-a+1:1:b-1;
subplot(2,2,3);
stem(t,Z);
title('Convolution by Toeplitz Matrix');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,4);
stem(t,A);
title('Convolution by Inbuilt Function');
xlabel('Index ->');
ylabel('Value ->');
dim = [0.11 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');