%Author- Mrigakshi Pandey (2015UEC1380)
% Convolution by Vector Rotation
%.......................................

close all;
clear all;
clc;

X=input('Input your Vector: ');
a=length(X);
tx=1:1:a;

Y=input('Input another Vector for Convolution: ');
b=length(Y);
ty=1:1:b;
subplot(2,2,1);
stem(tx,X);
title('First Vector');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,2);
stem(ty,Y);
title('Second Vector');
xlabel('Index ->');
ylabel('Value ->');
n=a+b-1;
A=conv(X,Y);

X=[zeros(1,n-a),X];
Y=[fliplr(Y),zeros(1,n-b)];

for i=1:1:n
    Z(i)=0;
    for j=1:1:n
        Z(i)=Z(i)+(X(j)*Y(j));
    end
    Y=[0,Y];
end
t=-a+1:1:b-1;
subplot(2,2,3);
stem(t,Z);
title('Convolution by Vector Rotation');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,4);
stem(t,A);
title('Convolution by Inbuilt Function');
xlabel('Index ->');
ylabel('Value ->');
dim = [0.11 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');