%Author- Mrigakshi Pandey (2015UEC1380)
% Circular Convolution by Toeplitz Matrix
%.......................................

close all;
clear all;
clc;

X=input('Input First Vector: ');
a=length(X);

Y=input('Input Second Vector: ');
b=length(Y);

if a>b
    Y=[Y,zeros(1,a-b)];
    b=a;
end

if b>a
    X=[X,zeros(1,b-a)];
    a=b;    
end

t=1:1:b;

subplot(2,2,1);
stem(X);
title('First Vector');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,2);
stem(Y);
title('Second Vector');
xlabel('Index ->');
ylabel('Value ->');

A=cconv(X,Y,b);

Xt=X';
temp=X';

for i=1:1:b-1
    temp=[0;temp];
    temp(1)=temp(b+1);
    temp=temp(1:b);
    
    Xt=[Xt,temp];
end

Z=Xt*Y';

subplot(2,2,3);
stem(t,Z);
title('Convolution by Toeplitz Matrix');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,4);
stem(t,A);
title('Convolution by Inbuilt Function');
xlabel('Index ->');
ylabel('Value ->');
dim = [0.11 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');