%Author- Mrigakshi Pandey (2015UEC1380)
% Circular Convolution by vector rotation
%.......................................

close all;
clear all;
clc;

X=input('Input First Vector: ');
a=length(X);

Y=input('Input Second Vector: ');
b=length(Y);

if a>b
    Y=[Y,zeros(1,a-b)];
    b=a;
end

if b>a
    X=[X,zeros(1,b-a)];
    a=b;    
end

t=1:1:b;

subplot(2,2,1);
stem(X);
title('First Vector');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,2);
stem(Y);
title('Second Vector');
xlabel('Index ->');
ylabel('Value ->');

A=cconv(X,Y,b);

X=fliplr(X);

for i=1:1:b
    Z(i)=0;
    for j=1:1:b
        Z(i)=Z(i)+(X(j)*Y(j));
    end
    Y=[0,Y];
    Y(1)=Y(b+1);
    Y=Y(1:b);
end

Z=fliplr(Z);


subplot(2,2,3);
stem(Z);
title('Convolution by Toeplitz Matrix');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,4);
stem(A);
title('Convolution by Inbuilt Function');
xlabel('Index ->');
ylabel('Value ->');
dim = [0.11 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');