%Author- Mrigakshi Pandey (2015UEC1380)
% DFT
%.......................................

close all;
clear all;
clc;

t=0:(1/512):(1-(1/512));
N=512;
x=10*sin(2*pi*10*t)+20*sin(2*pi*50*t)+10*sin(2*pi*80*t);
subplot(3,1,1)
stem(x);
xlabel('index->');
ylabel('value->');
title('Given Vector');
axis([0 100 -40 40]);

for k=0:1:N-1
    for n=0:1:N-1
        A(k+1,n+1)=conj(exp(-1*i*2*pi*k*n/N));
    end
end

X=(A*x')'
subplot(3,1,2)
plot(t,abs(X));
xlabel('index->');
ylabel('value->');
title('DFT by program');


f=512.*t;
subplot(3,1,3);
plot(f,abs(X));

dim = [0.11 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');