%Author- Mrigakshi Pandey (2015UEC1380)
% Assignment (Cross-correlation)
%.......................................

close all;
clear all;
clc;

X=input('Input your Vector: ');
a=length(X);

Y=input('Input another Vector for Correlation: ');
b=length(Y);

subplot(2,2,1);
stem(X);
title('First Vector');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,2);
stem(Y);
title('Second Vector');
xlabel('Index ->');
ylabel('Value ->');
n=a+b-1;
A=xcorr(X,Y);

Y=Y';
X=fliplr(X);
X=[X,zeros(1,n-a)]';


Xt=X;

for i=1:1:b-1
    Xt=[Xt,circshift(X,1)];
    X=circshift(X,1);
end

Z=Xt*Y;
Z=Z';
Z=fliplr(Z);
t=1:1:a+b-1;
subplot(2,2,3);
stem(Z);
title('Correlation by Toeplitz Matrix');
xlabel('Index ->');
ylabel('Value ->');

subplot(2,2,4);
A=A(1:a+b-1);
stem(t,A);
title('Correlation by Inbuilt Function');
xlabel('Index ->');
ylabel('Value ->');
dim = [0.11 0.081 0 0];
str = {'Generated by:','Mrigakshi Pandey (2015UEC1380)'};
annotation('textbox',dim,'String',str,'FitBoxToText','on');